### ISSUE TITLE
PHP heredocs

### ISSUE THREAD

**Issue by b21e** [jamalsenouci/sublimetext-syntaxfold#10]
Just an idea for improvement: Please support [PHP heredocs] (http://php.net/language.types.string#language.types.string.syntax.heredoc).

**Comment by jamalsenouci** [comment]
I'm not familiar with php, what would need changing to support this

**Comment by b21e** [comment]
It's a way to escape arbitrary text. You have the same concept in the Unix Shell. Here an example:
    cat << HEREDOC
    arbitrary text not containing H-E-R-E-D-O-C
    HEREDOC
or:
    cat << OTHER_name
    arbitrary text not containing herestring O-T-H-E-R-_-n-a-m-e
    OTHER_name
The point is that you can redefine your quotes (in this case HEREDOC or OTHER_name) as needed.

**Comment by jamalsenouci** [comment]
You could define a marker in the config as follows:
<code>
		{
			"endMarker": "\\<\\<\\<HEREDOC",
			"name": "test",
			"startMarker": "HEREDOC"
		}
</code>
but it does require a specified string which may not be exactly what you want. I think supporting the general pattern would likely fit better within a php plugin.
