### ISSUE TITLE
Java-like comment support

### ISSUE THREAD

**Issue by jkentjnr** [jamalsenouci/sublimetext-syntaxfold#11]
Hi there,

I'm trying to get support for COD - using a syntax like below.  Any thoughts ... I don't know if it will work because the start and end tags are formatted as comments by the syntax highlighter.

Any help would be great.  Cheers.

/***
@class QueryRequest
***/
public class QueryRequest {

/***
    @property BaseObject
        @type String
        @summary Stores the name of the base object of the query request.
***/
    public String BaseObject { get; set; }
}

**Comment by jamalsenouci** [comment]
Hi, 
you can do it but because the asterix is a special character you have to escape it with a forward slash so * becomes /*, it ends up looking quite messy.

you should be able to get it working by adding a custom marker as follows

<code>		
			"endMarker": "/\*/\*/\*/",
			"name": "test",
			"startMarker": "//\*/\*/\*"
		}
</code>
