### ISSUE TITLE
[feature] folder sign keeping when unfolding is executed.

### ISSUE THREAD

**Issue by GeekMe93** [jamalsenouci/sublimetext-syntaxfold#13]
Hi, I notice that when I fold all the regions, the triangle folder sign will appear on the specific position. This is great, but the problem is that when I unfold single region by clicking the triangle, the original sign will disappear. Can you still keep the triangle unfold sign when I do unfold operation?

Thank you!

**Comment by jamalsenouci** [comment]
Hi, I think this is a duplicate of issue #3 I still haven't got around to looking at this properly yet but will take another look now
