### ISSUE TITLE
[Feature Request] save folding state

### ISSUE THREAD

**Issue by hirnwunde** [jamalsenouci/sublimetext-syntaxfold#15]
It is possible to save the state of folding regions when closing a file to load it again when reopening the file again.

The shortcuts [ALT]+[0] and [ALT]+[SHIFT]+[0] are known to me, but somtimes i had some regions folded others dont folded.

The informations of the folding states could be stored in the fileheader itself (like Vims modeline [see here](http://vim.wikia.com/wiki/Modeline_magic)) or as dotfile inside the directory of the file.
Ideally changeable via User-Settings of SyntaxFold.

**Comment by jamalsenouci** [comment]
This is a good idea, I'll have a look into the best way to integrate this

**Comment by kimaldis** [comment]
Buffersroll will do this for you. be sure to set _"synch_folds": true_ in Bufferscroll's preferences

**Comment by jamalsenouci** [comment]
ah cool, i'll close this issue as there's not much point replicating that functionality
