### ISSUE TITLE
2.0.0  just updated doesn't work

### ISSUE THREAD

**Issue by maximilianahead** [jamalsenouci/sublimetext-syntaxfold#20]
I am using c# coding.
This plugins suddenly stopped working on this previous update, but I tried it a lot working now.
//syntax_fold.sublime-settings
{
	"endMarker": "#endregion",
	"name": "C#",
	"scope": "source.cs", <-- Add line
	"startMarker": "#region"
},
 I hope this will help:)

**Comment by jamalsenouci** [comment]
Could you try removing the second line ("name": "C#",) and report back?

**Comment by jamalsenouci** [comment]
Yes the 2.0 update resulted in a breaking change for the sublime-settings file so that will need updating - see the readme for more information on how to do this

**Comment by maximilianahead** [comment]
I read the readme.md but i did not know why the require params "scope" disappeared by latest update.
But I understood need it for some reasons.
Thank you.=)

**Comment by maximilianahead** [comment]
I'm sorry I thought scope params was exist since previous version...
