### ISSUE TITLE
Fold to end of file

### ISSUE THREAD

**Issue by Adarma** [jamalsenouci/sublimetext-syntaxfold#21]
Is it possible to fold from a startMarker to the end of the file?
eg. With "startMarker" = "##" and no "endMarker" defined:

```
## Section 1
This is foldable
## Section 2
This is not foldable
```

Thanks for the plugin.

**Comment by jamalsenouci** [comment]
It should be a pretty easy fix, I'll be able to do this today

**Comment by Adarma** [comment]
Thanks. Works well
