### ISSUE TITLE
does absolutely nothing

### ISSUE THREAD

**Issue by phil123456** [jamalsenouci/sublimetext-syntaxfold#24]
Hello,

I tried folding html and js, nothing happens

sometimes doing alt+0 or alt+1 switch the current edited document to another one, but appart from that

my code is never altered

waht am I missing ?

thanks

**Comment by jamalsenouci** [comment]
This plugin is not really going to be suited to html and javascript it's for folding code regions.

**Comment by phil123456** [comment]
oh sorry 
I forgot html meant bread, js meant spagetthi, code folding was in fack cleaning the dog's ass 
... and that all of these had nothing to do with coding
