### ISSUE TITLE
[feature] Automatically create folding regions

### ISSUE THREAD

**Issue by woollybogger** [jamalsenouci/sublimetext-syntaxfold#3]
It would be nice to have the folding arrow automatically appear once a valid folding region section has been typed. Hopefully you can see what I mean from this image:

![foldingregion](https://cloud.githubusercontent.com/assets/5128013/6283099/4726aece-b894-11e4-968e-bf38b43ae2c8.png)

**Comment by jamalsenouci** [comment]
I agree, it's one of the things that I always found annoying. I planned to implement this at one point but never got around to figuring out how. Unfortunately, I have limited time to work on it right now but maybe in a couple of months or so.

**Comment by woollybogger** [comment]
Yeah I understand it can be difficult to find time for open source work. Thank you for acknowledging this in the meantime.

**Comment by jamalsenouci** [comment]
It certainly can! No problem, thanks for the contribution.

**Comment by iBEASTMODE** [comment]
+1

This would be a great feature : )

**Comment by benruijl** [comment]
+1

Would be great!

**Comment by IPWright83** [comment]
+1 

I actually assumed this is how it worked... when I couldn't seem to get any arrows (or actually locate my key bindings) I gave up and un-installed it. Now I'm thinking I was a little hasty. Maybe in the meantime the readme needs updating to just illustrate what it actually does.

**Comment by jamalsenouci** [comment]
I'm pretty sure it's not possible to do this, the control of the arrows is an internal function that is not exposed. So although it calls that function to create them when we fold a region, it is not possible to automatically detect a syntax region and create the arrows.
