### ISSUE TITLE
Issue : "Bookmark" Artifacts

### ISSUE THREAD

**Issue by FiCode** [jamalsenouci/sublimetext-syntaxfold#4]
This is an awesome plugin : )

However, I am currently running into the following issue:

After folding & unfolding the code several times, I am left with multiple artifacts of "bookmark" symbols in the left gutter.  Is there a way to disable bookmarks from SyntaxFold entirely?  I do not see a use for them, as regular code fold symbols should be all that is needed, & the bookmark symbols obscure them.

![screenshot_030315_060526_pm](https://cloud.githubusercontent.com/assets/10906415/6474575/eff932d0-c1cf-11e4-9457-af40a5f83017.jpg)

**Comment by jamalsenouci** [comment]
Thanks! I'm a little busy at the moment but I should be able to look into this shortly. It should be perfectly doable.

**Comment by jamalsenouci** [comment]
I haven't been able to replicate this issue. what os and version of sublime text are you using
