### ISSUE TITLE
Update package control

### ISSUE THREAD

**Issue by phillipse01** [jamalsenouci/sublimetext-syntaxfold#42]
Package control still picks up the older version before fix #40 - update package control at https://packagecontrol.io/packages/SyntaxFold

**Comment by jamalsenouci** [comment]
this is now fixed - was missing a version bump

**Comment by phillipse01** [comment]
Awesome! Glad to see we just had to update "messages.json" and the changelog. Just posted a quick fix for the 2.3.0 md messages as the title was old.

**Comment by phillipse01** [comment]
a67edde07056fb677d19beb1d387b57bb6237276
also added 2.3.0 tag
