### ISSUE TITLE
Doesn't seem to work in SublimeText 4

### ISSUE THREAD

**Issue by goatcheesay** [jamalsenouci/sublimetext-syntaxfold#43]
Greetings!

I hope this finds you well.  Having gone along with the recent ST4 update, I believe SyntaxFold might need an update to function.  When ya go to fold all the code, it folds it according to ST's syntax.  I've tried resinstalling, etc., doesn't seem to help.  Thanks in advance for you time and consideration.  Cheers!

**Comment by jamalsenouci** [comment]
closing following successful merge of #44

**Comment by FauxHibou** [comment]
Thank you folks!  I appreciate your help a lot.  The package is so important that I had done a clean re-install of ST3 just to get it back.  Cheers, have a good one!
