### ISSUE TITLE
Fold all not working

### ISSUE THREAD

**Issue by dwhenson** [jamalsenouci/sublimetext-syntaxfold#45]
I have the toggle and unfold commands working fine, but fold all doesn't seem to work at all. I noted that in the status bar a message appears saying '1 regions folded' but no code is folded at all. I have tried with different key bindings but it doesn't work. I am on OS X in ST4. Thanks for any advice.

**Comment by mattwidmann** [comment]
Seems like @jamalsenouci just needs to push v2.4.0 to Package Control? Or cut a release tag for 2.4.0 in Github?

**Comment by jamalsenouci** [comment]
yes thanks @mattwidmann I missed that step, done now and is working on ST4
