### ISSUE TITLE
Pattern regions

### ISSUE THREAD

**Issue by ambs** [jamalsenouci/sublimetext-syntaxfold#7]
Hello

Was trying to use syntaxfold for LaTeX but I am not sure if I am using it in the wrong way, or if it just doesn't work for what I want.

Basically, my config looks like:
````````
		{
			"endMarker": "\\end{",
			"name": "LaTeX",
			"startMarker": "\\begin{"
		},
`````````
and as you might expect, marker lines continue with more characters up to the end of the line. 

It seems it doesn't work with this kind of markers at the moment. I am right?

Also, does it have any problem with nested regions?

best,

**Comment by ambs** [comment]
This works:

		"endMarker": "\\\\end\\{",
		"startMarker": "\\\\begin\\{"

But that is not practical. But in other way, I wonder if I can use references...  in order to say the begin{foo} needs to be closed by an end{foo}. That would be awesome, specially given currently proper nesting is not working.

**Comment by ambs** [comment]
Gah, it was a good try:

		"endMarker": "\\\\end\\{([^}]+)\\}",
		"startMarker": "\\\\begin\\{\\1\\}",

And, by the way, it would be great if the triangle indicator could appear automatically for the current region.

**Comment by jamalsenouci** [comment]
Sublime text should already support folding latex. Make sure the syntax is set to latex by going to view-->syntax and select latex. Then go to edit-->code folding and select fold all



—
