### ISSUE TITLE
*--#[ and *--#] region markers not working

### ISSUE THREAD

**Issue by benruijl** [jamalsenouci/sublimetext-syntaxfold#9]
When I define the following region

		{
			"endMarker": "*--#]",
			"name": "FORM",
			"startMarker": "*--#["
		}

I cannot fold.

**Comment by jamalsenouci** [comment]
Hi,

This is happening because your markers contain special characters so you need to escape them if you use the following code then it should fold as expected:
<code>
	{
			"endMarker": "\\\\*--#\\\\]",
			"name": "test",
			"startMarker": "\\\\*--#\\\\["
		}
</code>

**Comment by benruijl** [comment]
Thanks. This fixes it!
